misc

diff --git a/bin/pape b/bin/pape
--- a/bin/pape
+++ b/bin/pape
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 set -euo pipefail
+if pidof swaylock; then echo pape exiting because system locked >&2; exit 1; fi
 if [ $# -eq 0 ]; then pic="$(sxiv -ort ~/pics/wallpapers | head -n1)"
 elif [ "$1" = "?" ]; then pic="$(find "$HOME/pics/wallpapers" -type f | shuf -n1)"
-elif [ -e "$1" ]; then pic="$1"
-else echo "$1 not found"; exit 1
-fi
+else pic="$1"; fi
+if [ ! -e "$1" ]; then echo "$1 not found" >&2; exit 1; fi
 pic="$(realpath "$pic")"
 location="$HOME/.config/wallpaper"
 ln -sf "$pic" "$location"
