older & wiser

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,50 +1,37 @@
 #!/usr/bin/env bash
 set -euo pipefail
-
-function helptext() {
-	cat <<EOH
-Usage: $0 [OPTS] [DIR...]
-
-OPTS:
-	-f	Force overwrites
-	-h	Help
-EOH
-}
-
 FORCE=
-SEARCH=()
-# FIXME
-while getopts "hf" o; do case $o in
-	h) helptext; exit 0 ;;
+while getopts "fH:h" o; do case $o in
 	f) FORCE=1 ;;
-	*) SEARCH+=("$OPTARG");;
+	H) HOME="$(realpath "$OPTARG")";;
+	h | *) cat <<EOH
+$0 [OPTS] [DIR...]
+OPTS:
+	-f	force overwrite
+	-H<DIR>	non-\$HOME homedir
+	-h	halp
+EOH
+	;;& h) exit 0 ;; *) exit 1;;
 esac done
 shift $((OPTIND-1))
-SEARCH+=("$@")
-
-if [ $# -eq 0 ]; then
-	SEARCH=('.')
-fi
-
-find "${SEARCH[@]}" -name loc | while read -r loc; do
-	fromdir="$(dirname "$loc")"
+if [ $# -eq 0 ]; then set .; fi
+# FIXME: don't leak opts to find if users pass opts after dirs
+find "$@" -name loc | while read -r loc; do
+	# shellcheck disable=SC2094
 	while read -r line; do
-		from="$fromdir/$(cut -d' ' -f1 <<<"$line")"
-		to="${line##* }"
-		tod="$(dirname "$HOME/$to")"
-		if [ -e "$HOME/$to" ]; then
+		to="$HOME/${line##* }"
+		tod="$(dirname "$to")"
+		from="$(realpath --relative-to="$tod" "$(dirname "$loc")/$(cut -d' ' -f1 <<<"$line")")"
+		if [ -e "$to" ]; then
 			if [ -z "$FORCE" ]; then
-				echo "error: ~/$to already exists" >&2
-				echo "to overwrite existing files run with -f" >&2
+				echo "error: $to already exists" >&2
+				echo "to overwrite run with -f" >&2
 				exit 1
 			else
 				# shellcheck disable=SC2115
-				rm -rf "$HOME/$to"
+				rm -rf "$to"
 			fi
 		fi
-		# shellcheck disable=SC2088
-		echo "~/$to <- $from"
-		mkdir -p "$tod"
-		ln -fns "$(realpath "$from" --relative-to="$tod")" "$HOME/$to"
+		echo "$to -> $from"; mkdir -p "$tod"; ln -fns "$from" "$to"
 	done <"$loc"
 done
